name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: Instalar poetry
        run: pipx install poetry
        
      - name: Copia arquivos do repositório
        uses: actions/checkout@v7

      - name: Instalar dependências
        run: poetry install --no-root
        
      - name: Executar lint
        run: poetry run poe lint

      - name: Executar testes
        run: poetry run poe test

    env:
        ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
        ALGORITHM: ${{ secrets.ALGORITHM }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRECT_KEY: ${{ secrets.SECRECT_KEY }}